# Run Travis CI for R using https://eddelbuettel.github.io/r-travis/

language: c

sudo: required

dist: trusty

before_install:
  #- curl -OLs http://eddelbuettel.github.io/r-travis/run.sh && chmod 0755 run.sh
  - curl -OLs https://raw.githubusercontent.com/joshuaulrich/r-travis/master/run.sh && chmod 0755 run.sh
  - ./run.sh bootstrap

install:
  - ./run.sh install_aptget r-cran-runit r-cran-zoo
  - ./run.sh install_github joshuaulrich/xts

script:
  #- ./run.sh run_tests
  - travis_wait ./run.sh run_tests

after_failure:
  - ./run.sh dump_logs

notifications:
  email:
    on_success: change
    on_failure: change
